### PR TITLE
Add online documentation with pkgdown and cleanup a bit

### PR DESCRIPTION
**Pull request by vandenman**
Check it out [here](https://vandenman.github.io/jaspGraphs/).

Adds online documentation for jaspGraphs that is regenerated on each push through `pkgdown.yml`. Note: this pr should **not** be merged as is because the github actions script only runs on branches called `pkgdown`, which I'll change to master before merging.

I'm planning to do the same for jaspResults, you can already try it out [here](https://vandenman.github.io/jaspResults/)

In addition, this PR does some cleanup:

- Drop `stringr` as a dependency in favor of regex with base R.
- Use `lifecycle` for deprecating things like `jaspTools` does. This does not introduce an additional dependency since `scales` (dependency of `ggplot2`) already imports it.
- Update roxygen2, which is why every Rd file changed.
- Add some badges to the readme (e.g., one that takes you to the documentation)

It should also be possible to use jasp-stats.org as a domain, but let's do that separately.

### CODE REVIEW

**Comment by boutinb** [comment]
Should this PR be in 0.15?

**Comment by amirmasoudabdol** [comment]
This looks nice! 👍🏼 

PS. If you are interested, I once developed a proper template for {pkgdown}, called [{preferably}](https://preferably.amirmasoudabdol.name/).

**Comment by vandenman** [comment]
> Should this PR be in 0.15?

No, this is for 0.16.

A template would be nice, although it also makes sense to create a jasp-specific one.

**Comment by amirmasoudabdol** [comment]
A few suggestions,

- The blue ribbon on top doesn't look great, especially on a documentation website. The green on at the bottom is forgivable, but the blue one on the top makes the website look like a hotel website! In addition, then you have to deal with contrast, readabilities, and accessibilities issues.
	- Maybe if you really squeeze into the navbar, it would be better, but I suspect it's going to be crowded.
- Overwriting the width is very tricky these days, considering many screen sizes, orientation, etc. You should avoid it.
  
CleanShot 2021-09-27 at 09 47 02

IMG_2312

- The colour scheme for the syntax is very aggressive, and the orange doesn't have a great contrast with white, see [here](https://webaim.org/resources/contrastchecker/). I know some scheme are actually using it, but it's not really great!
- Maybe use the "JASP Graph" as the main title of the page, `jaspGraphs` looks weird!

**Comment by vandenman** [comment]
> The blue ribbon on top doesn't look great, especially on a documentation website. The green on at the bottom is forgivable, but the blue one on the top makes the website look like a hotel website! In addition, then you have to deal with contrast, readabilities, and accessibilities issues. 

My goal was to mimic how jasp looks in general, see
- https://jasp-stats.org/
- the about window: image 

I'd rather not invent a completely different look and feel, in particular since the page should be accessible through https://jasp-stats.org/ in the future.


> Overwriting the width is very tricky these days, considering many screen sizes, orientation, etc. You should avoid it.

I did not overwrite the width? I overwrote the height, because the default height of the body of pkgdown does not change when scrolling. When you omit `height: auto;` there are still elements below the bottom green wave when you scroll down.

image

I do notice that the padding is not doing what I wanted it to do, which is probably what caused the issues with resizing. I think I can just delete that though.

> Maybe use the "JASP Graph" as the main title of the page, jaspGraphs looks weird!

Once, we had some discussions about camelcasing versus other things. In fact, I originally called the package `JASPgraphs` and not `jaspGraphs`. Your suggestion would also imply:

- `jaspBase` -> `JASP Base`
- `jaspResults` -> `JASP Results`

I'm fairly certain that the people who objected against `JASPgraphs` in the past will also object to this :stuck_out_tongue:.

I'd prefer to do something like `pkgname: <one sentence summary>`, like:

- `jaspGraphs: helper functions for plots in JASP`.
- `jaspResults: a bridge between R and JASP`.
- `jaspBase: helper functions for writing JASP modules`.

The actual sentences can still be changed, of course.

> The colour scheme for the syntax is very aggressive

I copied this from another template and didn't put too much effort into this (yet), feel free to make suggestions/ play around with it.

**Comment by amirmasoudabdol** [comment]
> My goal was to mimic how jasp looks in general

I see that, but don't do that. It barely works on the app. It's straight out of early 2000 if you ask me! The whole persistence colorful welcome screen is a very strange and old-fashioned concept! 😅 It's fine as a splash screen, or in the About, but as the app background, I don't get it! 

> I do notice that the padding

Oh yes, I referred to `width` incorrectly. 

I don't mind the naming scheme of the package itself, but for the website, I think we should use the title instead of the package name. The package name can appear on the navbar, and if we really want to we can have a tiny subtitle with the package name and description.

I think we are really better off with the default, or if you want to somehow resemble JASP, start with one of these, and tweak the color a bit, https://bootswatch.com/3/, and brings it close to JASP colors. {pkgdown} already supports this a bit. You can choose any of those, and it pulls it.

Also, be aware that {pkgdown} is going to be updated to BS4 soon, and this might break any custom tweakings, especially `navbar` stuff.

**Comment by vandenman** [comment]
> I see that, but don't do that. It barely works on the app. It's straight out of early 2000 if you ask me! The whole persistence colorful welcome screen is a very strange and old-fashioned concept! sweat_smile It's fine as a splash screen, or in the About, but as the app background, I don't get it!

That sounds like a very personal opinion on the look and feel. If you want to redesign the entire look and feel of JASP, I'd suggest you discuss it with EJ first. Regardless, I don't think this PR is a good starting point for discussing a complete redesign, let alone implementing it. These decisions are simply not ours to make.

Until we have a new design, I think it makes sense to value consistency within jasp over the actual look.

**Comment by EJWagenmakers** [comment]
"It's straight out of early 2000 if you ask me! The whole persistence colorful welcome screen is a very strange and old-fashioned concept!"

Well it was designed a few years ago, by a hip company :-) I think we'll stick with it for the time being.

**Comment by amirmasoudabdol** [comment]
I know it's personal, that's why I said "if you ask me"! 😅  And, no, I don't want to redesign the entire JASP, but I think some incremental changes would help keeping it up-to-date and modern along the way. For this PR, I was trying to say that if we cannot consider different aspects of a design, we better off sticking to defaults and standards.

**Comment by vandenman** [comment]
ok, @amirmasoudabdol I've reverted the custom design. Let's just stick to pkgdown's defaults for now and maybe we should once have a meeting where we pick a design the entire team agrees on (and then we can stick to that).

Any further non-design-related comments?

**Comment by amirmasoudabdol** [comment]
Sorry @vandenman, I completely missed this message. If we go with the default, I don't have any more comments on the design. 

PS. As soon as the new `{pkgdown}` is out, and I'm done with the build system, we can discuss a minor redesign to the default team to give it a bit of a JASP feeling!

**Pull request merged**
