### PR TITLE
Add error message for base plots (functions)

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/jasp-test-release/issues/1529

The error message is now:
image

### CODE REVIEW

**Comment by EJWagenmakers** [comment]
1. "can not" -> cannot
2. Do we need the colon?
3. "...was created in base R" maybe add "instead of ggplot" for enhanced clarity?

**Comment by vandenman** [comment]
So this is the new errormessage:
image

Removing the `:` is definitely nicer, although this might be slightly more difficult to translate.

**Comment by EJWagenmakers** [comment]
great!

**Comment by amirmasoudabdol** [comment]
I would say you can probably even replace "this figure" with an "it" pronoun. It makes the sentence simpler, and more uniform.

**Review by Kucharssim — APPROVED** [review]

**Pull request merged**
