### PR TITLE
Add custom geom for abline that respect the axes

### PR DESCRIPTION
**Pull request by vandenman**
Fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/1212

Feel free to postpone this until after the 0.15 release! It shouldn't be merged before that anyway.

Right now, we often use `geom_line` instead of `geom_abline`, because EJ does not like the way ggplot2 abline looks (it exceeds the axis breaks). However, when doing plotediting the ablines with geom_line may disappear (see the linked issue). This PR adds a custom abline geom that is an alternative for the geom_line approach, because the bounds of the line are determined at draw time (by looking at the extrema of the axes breaks). The syntax should be identical to `geom_abline`. The function is called `geom_abline2` to avoid namespace clashes with ggplot2.

Running the example should show output like this:

``` r
library(ggplot2)
library(jaspGraphs)
#> 
#> Attaching package: 'jaspGraphs'
#> The following objects are masked from 'package:ggplot2':
#> 
#>     geom_line, geom_point, scale_x_continuous, scale_y_continuous
dfRect <- data.frame(xmin = -10, ymin = -10, xmax = 10, ymax = 10)
basePlot <- ggplot(data = dfRect, aes(xmin = xmin, ymin = ymin, ymax = ymax, xmax = xmax)) +
  geom_rect(fill = NA, color = "black") +
  geom_rangeframe() +
  themeJaspRaw(legend.position = "right")

slopes <- seq(-5, 5, length.out = 15)
ints   <- seq(-2, 2, length.out = length(slopes))
basePlot +
  geom_abline2(intercept = ints - 2, slope = slopes, method = "breaks",  color = "green") +
  geom_abline2(intercept = ints + 2, slope = slopes, method = "ggplot2", color = "red") +
  ggtitle("specify 'method' manually")
```

``` r
dfAbline <- data.frame(
  intercept = -9:8,
  slope = 0.35,
  method = rep(c("ggplot2", "breaks"), 9)
)

basePlot +
  geom_abline2(data = dfAbline, mapping = aes(
    intercept = intercept, slope = slope, method = method, color = method
  ), show.legend = TRUE) +
  ggtitle("specify 'method' through aes")
```

``` r
basePlot + geom_abline2(data = dfAbline, mapping = aes(
    intercept = intercept, slope = slope, color = method
  )) +
  ggtitle("if method is not specified, 'breaks' is used as a default")
```

``` r
dfAbline <- data.frame(
  slope = c(Inf, Inf),
  intercept = 0,
  method = rep(c("ggplot2", "breaks"), 2)
)

basePlot +
  geom_abline2(data = dfAbline, mapping = aes(
    intercept = intercept, slope = slope, method = method, color = method
  ), show.legend = TRUE) +
  ggtitle("more reasonable behavior for infinite slopes")
```

<sup>Created on 2021-09-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Review by Kucharssim — APPROVED** [review]
Code is really good, the functionality seems to work as expected!

**Comment by AlexanderLyNL** [comment]
Thanks for the review!

**Comment by Kucharssim** [comment]
A little bit too late the review, sorry about that!

**Comment by AlexanderLyNL** [comment]
Really no worries, I see that you're working your ass off here. Please rest.

**Pull request merged**
